swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: 1.0.0
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction API
      description: API for receiving all transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true   
        - in: path
          name: month
          description: Transaction via month
          required: true
          schema:
            type: integer   
        - in: path
          name: account
          description: Transaction via account
          required: true
          schema:
            type: integer 
      produces:
        - application/jsony
      responses:
        "200":
          description: Transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/TransactionsByAccount"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error        
  /transaction:
    post:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction API
      description: API for create a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Payload transaction
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successfully
          schema:
            $ref: "#/definitions/TransactionResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /transaction/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction API
      description: API for receiving a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: id
          description: Transaction id
          required: true
          schema:
            type: integer
      produces:
        - application/json
      responses:
        "200":
          description: transaction retrieved successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction API
      description: API for updating a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: id  
        - in: body
          name: body
          description: Update transaction attributes
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction retrieved successfully
          schema:
            $ref: "#/definitions/TransactionResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction API
      description: API for delete a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: id  
      produces:
        - application/json
      responses:
        "200":
          description: Transaction remove successully
          
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transaction:
    properties:
      date:
        type: string
        description: date transaction
      desciptionTransaction:
        type: string
        description: transaction details
      amount:
        type: string
        description: transaction amount
      balance:
        type: string
        description: transaction balance 
      type:
        type: string
        description: transaction type 
      category:
        type: string
        description: transaction category 
      note:
        type: string
        description: transaction balance   
          
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  
  TransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
      
  TransactionsByAccount:
    type: object
    properties:
      account:
        type: object
        properties:
          id:
            type: string
      transactions:
        type: array
        items:
            $ref: '#/definitions/Transaction' 
                  
